[package]
name = "gitolfs3-common"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
chrono = "0.4"
hmac-sha256 = "1.1"
subtle = "2.6"
serde = { version = "1", features = ["derive"] }
