.TH GITOLFS3-SHELL 1 2024-04-29 Gitolfs3 "Gitolfs3 Manual"
.SH NAME
gitolfs3-shell \- Gitolfs3 shell
.SH SYNOPSIS
.B gitolfs3-shell
-c <command>
.SH DESCRIPTION
.B gitolfs3-shell
is the Gitolfs3 shell, usable as the default shell for the \fIgit\fR user.
.SH COMMANDS
.TP
.B git-receive-pack \fR<repsitory>\fB
Alternatively, using \fBgit receive-pack\fR is also allowed.
No other arguments nor options than indicated above are processed nor allowed.
See
.BR git-receive-pack (1).
.TP
.B git-upload-archive \fR<repsitory>\fB
Alternatively, using \fBgit upload-archive\fR is also allowed.
No other arguments nor options than indicated above are processed nor allowed.
See
.BR git-upload-archive (1).
.TP
.B git-upload-pack \fR<repsitory>\fB
Alternatively, using \fBgit upload-pack\fR is also allowed.
No other arguments nor options than indicated above are processed nor allowed.
See
.BR git-upload-pack (1).
.TP
.B git-lfs-authenticate \fR<repository> upload/download\fB
Outputs a JSON document containing a reference to the Gitolfs3 Git LFS endpoint
for the indicated repository and an accompanying tag/MAC to authenticate with
the Gitolfs3 server.
Only valid for the indicated repository and operation.
This command is rewritten to \fIgitolfs3-authenticate\fR.
See
.BR gitolfs3-authenticate (1).
